name: Build AtoM Docker Image

on:
  push:
    branches:
      - qa/2.x

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Build and Push AtoM Image
      - name: Build and Push AtoM Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: olivergra/atom:latest
          platforms: linux/amd64,linux/arm64
          build-args: |
            ATOM_COVERAGE=false
          # cache-from: type=registry,ref=your-dockerhub-username/atom:cache
          # cache-to: type=inline
          secrets: |
            "api_token=${{ secrets.API_TOKEN }}"
          # secret-envs: |
          #  "API_TOKEN=API_TOKEN"
